// Auto-generated by sync.py from YouTube channel UC3JSfV8-K_ns4XI3uqfbrCQ
// Last synced: 2026-06-29T13:35:40+00:00

window.SYNCED_AT = "2026-06-29T13:35:40+00:00";
window.EPISODES = [
  {
    "n": 59,
    "id": "GFtYcvEftNQ",
    "title": "The Truth About SIPs: Most Investors Quit Too Early",
    "guest": "Bhartendra (solo)",
    "cat": "Investing",
    "views": null,
    "published": "2 days ago",
    "thumb": "https://i.ytimg.com/vi/GFtYcvEftNQ/hqdefault.jpg"
  },
  {
    "n": 58,
    "id": "sjjwPzGaF0I",
    "title": "Brazil, Taiwan, Korea: The International Investing Trap | Vijai Mantri",
    "guest": "Bhartendra (solo)",
    "cat": "Investing",
    "views": null,
    "published": "2 wk ago",
    "thumb": "https://i.ytimg.com/vi/sjjwPzGaF0I/hqdefault.jpg"
  },
  {
    "n": 57,
    "id": "Bnv2OOb5irs",
    "title": "SIP Works. I Have Seen It. | 30 Years of Mutual Fund Lessons | Bhalchandra Joshi",
    "guest": "Bhalchandra Joshi",
    "cat": "Investing",
    "views": null,
    "published": "3 wk ago",
    "thumb": "https://i.ytimg.com/vi/Bnv2OOb5irs/hqdefault.jpg"
  },
  {
    "n": 56,
    "id": "RqCy5D4f1Mg",
    "title": "Active vs Passive Funds: The Real Answer for Indian Investors",
    "guest": "Bhartendra (solo)",
    "cat": "Investing",
    "views": null,
    "published": "3 wk ago",
    "thumb": "https://i.ytimg.com/vi/RqCy5D4f1Mg/hqdefault.jpg"
  },
  {
    "n": 55,
    "id": "qR1CZ2dWr5Q",
    "title": "Is The India Story Over? - Groww MF's Equity Head Answers",
    "guest": "Anupam Tiwari",
    "cat": "Investing",
    "views": null,
    "published": "1 mo ago",
    "thumb": "https://i.ytimg.com/vi/qR1CZ2dWr5Q/hqdefault.jpg"
  },
  {
    "n": 54,
    "id": "C8lNnLi2Ppk",
    "title": "The Truth About This Market (No One Is Telling You This)",
    "guest": "Bhartendra (solo)",
    "cat": "Markets",
    "views": null,
    "published": "1 mo ago",
    "thumb": "https://i.ytimg.com/vi/C8lNnLi2Ppk/hqdefault.jpg"
  },
  {
    "n": 53,
    "id": "vIL33wnD5lk",
    "title": "Indian Markets Are Stuck. Here's What Nobody Is Telling You. | Debashish Bose",
    "guest": "Debashish Bose",
    "cat": "Markets",
    "views": null,
    "published": "2 mo ago",
    "thumb": "https://i.ytimg.com/vi/vIL33wnD5lk/hqdefault.jpg"
  },
  {
    "n": 52,
    "id": "IbD02i7Xvys",
    "title": "Your SIP Isn’t the Problem — You Are",
    "guest": "Bhartendra (solo)",
    "cat": "Investing",
    "views": null,
    "published": "2 mo ago",
    "thumb": "https://i.ytimg.com/vi/IbD02i7Xvys/hqdefault.jpg"
  },
  {
    "n": 51,
    "id": "6t5iaVbTb6U",
    "title": "Gold इतना महंगा है — फिर भी खरीदना सही है?",
    "guest": "Bhartendra (solo)",
    "cat": "Commodities",
    "views": null,
    "published": "2 mo ago",
    "thumb": "https://i.ytimg.com/vi/6t5iaVbTb6U/hqdefault.jpg"
  },
  {
    "n": 50,
    "id": "3-nQQHiUBdo",
    "title": "NASDAQ vs Nifty: Should Indians Invest Globally? | Mahmood Basha, Baroda BNP Paribas",
    "guest": "Bhartendra (solo)",
    "cat": "Global",
    "views": null,
    "published": "2 mo ago",
    "thumb": "https://i.ytimg.com/vi/3-nQQHiUBdo/hqdefault.jpg"
  },
  {
    "n": 49,
    "id": "ax-QZl75dbA",
    "title": "Buy Good, Buy Cheap, Stay Long — Kalpen Parekh, DSP Mutual Fund",
    "guest": "Kalpen Parekh",
    "cat": "Investing",
    "views": null,
    "published": "3 mo ago",
    "thumb": "https://i.ytimg.com/vi/ax-QZl75dbA/hqdefault.jpg"
  },
  {
    "n": 48,
    "id": "63j2xg2IGUU",
    "title": "5 Money Lessons from 40 Financial Experts",
    "guest": "Bhartendra (solo)",
    "cat": "Markets",
    "views": null,
    "published": "3 mo ago",
    "thumb": "https://i.ytimg.com/vi/63j2xg2IGUU/hqdefault.jpg"
  },
  {
    "n": 47,
    "id": "ldoFnNk6Z2g",
    "title": "Global Investing: Hype Hai Ya Opportunity?",
    "guest": "Kirtan Shah",
    "cat": "Global",
    "views": null,
    "published": "3 mo ago",
    "thumb": "https://i.ytimg.com/vi/ldoFnNk6Z2g/hqdefault.jpg"
  },
  {
    "n": 46,
    "id": "8jqbn8N1zeY",
    "title": "Why & How of Global Investing | Neil Borate",
    "guest": "Neil Borate",
    "cat": "Global",
    "views": null,
    "published": "3 mo ago",
    "thumb": "https://i.ytimg.com/vi/8jqbn8N1zeY/hqdefault.jpg"
  },
  {
    "n": 45,
    "id": "p-fDdN8Tm6w",
    "title": "Budget 2026: Tax Changes & Investing Playbook (Old vs New, HUF, LTCG, Allocation)",
    "guest": "Bhartendra (solo)",
    "cat": "Tax",
    "views": null,
    "published": "4 mo ago",
    "thumb": "https://i.ytimg.com/vi/p-fDdN8Tm6w/hqdefault.jpg"
  },
  {
    "n": 44,
    "id": "an4dvf0llMM",
    "title": "Markets Are Flat. Don’t Panic.The Real Wealth Game Is Patience.",
    "guest": "Bhartendra (solo)",
    "cat": "Wealth",
    "views": null,
    "published": "4 mo ago",
    "thumb": "https://i.ytimg.com/vi/an4dvf0llMM/hqdefault.jpg"
  },
  {
    "n": 43,
    "id": "nJkul5ypLTo",
    "title": "Is Your Portfolio Ready for 2026? Metal, Global Investing & Market Reality Check | Vijay Mantri",
    "guest": "Bhartendra (solo)",
    "cat": "Commodities",
    "views": null,
    "published": "4 mo ago",
    "thumb": "https://i.ytimg.com/vi/nJkul5ypLTo/hqdefault.jpg"
  },
  {
    "n": 42,
    "id": "dkQ9JW-Py9A",
    "title": "The biggest retirement risk is having only one income",
    "guest": "Bhartendra (solo)",
    "cat": "Retirement",
    "views": null,
    "published": "4 mo ago",
    "thumb": "https://i.ytimg.com/vi/dkQ9JW-Py9A/hqdefault.jpg"
  },
  {
    "n": 41,
    "id": "bah0QU9rHH8",
    "title": "Money Infinite Hai. Time Finite. | How Much Is Enough? | Karan Datta",
    "guest": "Bhartendra (solo)",
    "cat": "Investing",
    "views": null,
    "published": "4 mo ago",
    "thumb": "https://i.ytimg.com/vi/bah0QU9rHH8/hqdefault.jpg"
  },
  {
    "n": 40,
    "id": "rO_wCmULjyM",
    "title": "Why Silver Is Suddenly Expensive | War, Chips & Global Supply Explained",
    "guest": "Bhartendra (solo)",
    "cat": "Commodities",
    "views": null,
    "published": "5 mo ago",
    "thumb": "https://i.ytimg.com/vi/rO_wCmULjyM/hqdefault.jpg"
  },
  {
    "n": 39,
    "id": "0YwE4R-qPqA",
    "title": "Should You Buy a House or Keep Renting? 3 Expert Views, No Noise",
    "guest": "Bhartendra (solo)",
    "cat": "Real Estate",
    "views": null,
    "published": "5 mo ago",
    "thumb": "https://i.ytimg.com/vi/0YwE4R-qPqA/hqdefault.jpg"
  },
  {
    "n": 38,
    "id": "9SvVl5FALK4",
    "title": "How This Couple Built a ₹10 Crore Portfolio (Without Chasing Returns)",
    "guest": "Bhartendra (solo)",
    "cat": "Wealth",
    "views": null,
    "published": "5 mo ago",
    "thumb": "https://i.ytimg.com/vi/9SvVl5FALK4/hqdefault.jpg"
  },
  {
    "n": 37,
    "id": "zw_R7UEBvIQ",
    "title": "How to Become a Good Investor | Why the “Best Fund” Does Not Exist",
    "guest": "Bhartendra (solo)",
    "cat": "Investing",
    "views": null,
    "published": "6 mo ago",
    "thumb": "https://i.ytimg.com/vi/zw_R7UEBvIQ/hqdefault.jpg"
  },
  {
    "n": 36,
    "id": "LULE5jPzlo0",
    "title": "How Fund Managers Really Think: Stock Picking, Sector Cycles & Alpha Explained | Thomas Priju",
    "guest": "Thomas Priju",
    "cat": "Investing",
    "views": null,
    "published": "6 mo ago",
    "thumb": "https://i.ytimg.com/vi/LULE5jPzlo0/hqdefault.jpg"
  },
  {
    "n": 35,
    "id": "nT_TwhuIEPo",
    "title": "Why Investing Feels Hard (Even When It’s Simple)",
    "guest": "Mohit Bhatia",
    "cat": "Behaviour",
    "views": null,
    "published": "6 mo ago",
    "thumb": "https://i.ytimg.com/vi/nT_TwhuIEPo/hqdefault.jpg"
  },
  {
    "n": 34,
    "id": "QApks7nfIYI",
    "title": "How Ordinary Investors Build Extraordinary Wealth",
    "guest": "Bhartendra (solo)",
    "cat": "Wealth",
    "views": null,
    "published": "7 mo ago",
    "thumb": "https://i.ytimg.com/vi/QApks7nfIYI/hqdefault.jpg"
  },
  {
    "n": 33,
    "id": "seqzo4v-mlE",
    "title": "The Mindset That Built Financial Freedom at 40 (How He Did It) | Vinayak Sapre",
    "guest": "Vinayak Sapre",
    "cat": "Wealth",
    "views": null,
    "published": "7 mo ago",
    "thumb": "https://i.ytimg.com/vi/seqzo4v-mlE/hqdefault.jpg"
  },
  {
    "n": 32,
    "id": "0zxhAUjt-38",
    "title": "How Your PF Actually Gets Stuck (And What To Do About It)",
    "guest": "Bhartendra (solo)",
    "cat": "Retirement",
    "views": null,
    "published": "7 mo ago",
    "thumb": "https://i.ytimg.com/vi/0zxhAUjt-38/hqdefault.jpg"
  },
  {
    "n": 31,
    "id": "eQIdaQ9ml58",
    "title": "What’s the Point of Wealth If You’re Unhealthy?",
    "guest": "Bhartendra (solo)",
    "cat": "Retirement",
    "views": null,
    "published": "7 mo ago",
    "thumb": "https://i.ytimg.com/vi/eQIdaQ9ml58/hqdefault.jpg"
  },
  {
    "n": 30,
    "id": "pGdux5kFP3U",
    "title": "Why My Family Has Stayed 100% in Equity | CA Anuj Jain",
    "guest": "CA Anuj Jain",
    "cat": "Investing",
    "views": null,
    "published": "8 mo ago",
    "thumb": "https://i.ytimg.com/vi/pGdux5kFP3U/hqdefault.jpg"
  },
  {
    "n": 29,
    "id": "YOwd-k4VGPM",
    "title": "Why Mutual Funds Are Enough For Most Investors?",
    "guest": "Neil Borate",
    "cat": "Investing",
    "views": "12K",
    "published": "8 months ago",
    "thumb": "https://i.ytimg.com/vi/YOwd-k4VGPM/hqdefault.jpg"
  },
  {
    "n": 28,
    "id": "djx43Km1TSo",
    "title": "Bad Returns Are the BEST Returns | Vijai Mantri on Advisors, Mutual Fund SIP, Gold vs Equity",
    "guest": "Vijai Mantri",
    "cat": "Commodities",
    "views": "29K",
    "published": "8 months ago",
    "thumb": "https://i.ytimg.com/vi/djx43Km1TSo/hqdefault.jpg"
  },
  {
    "n": 27,
    "id": "7RURrUgKXig",
    "title": "Hidden Home-Buying Costs & Smart Buying Guide (India) | घर खरीदने से पहले ज़रूर देखें",
    "guest": "Bhartendra (solo)",
    "cat": "Real Estate",
    "views": "839",
    "published": "9 months ago",
    "thumb": "https://i.ytimg.com/vi/7RURrUgKXig/hqdefault.jpg"
  },
  {
    "n": 26,
    "id": "6H6GsUjCWfE",
    "title": "Stocks vs Mutual Funds: The Truth About SIP & Equity Investing | Sneha Jain",
    "guest": "Sneha Jain",
    "cat": "Investing",
    "views": "3.3K",
    "published": "9 months ago",
    "thumb": "https://i.ytimg.com/vi/6H6GsUjCWfE/hqdefault.jpg"
  },
  {
    "n": 25,
    "id": "ejC8nevgQb0",
    "title": "Where to Really Invest in 2025: Equity, Debt, Gold or Real Estate?",
    "guest": "Bhartendra (solo)",
    "cat": "Commodities",
    "views": "2.8K",
    "published": "9 months ago",
    "thumb": "https://i.ytimg.com/vi/ejC8nevgQb0/hqdefault.jpg"
  },
  {
    "n": 24,
    "id": "7YdiFShGRRQ",
    "title": "How to Create Wealth with Limited Income | Smart Investing Explained",
    "guest": "Bhartendra (solo)",
    "cat": "Wealth",
    "views": "2.3K",
    "published": "9 months ago",
    "thumb": "https://i.ytimg.com/vi/7YdiFShGRRQ/hqdefault.jpg"
  },
  {
    "n": 23,
    "id": "C966CXKS_tU",
    "title": "Why Retirement Scares Us (And How To Fix It)",
    "guest": "Bhartendra (solo)",
    "cat": "Retirement",
    "views": "1K",
    "published": "9 months ago",
    "thumb": "https://i.ytimg.com/vi/C966CXKS_tU/hqdefault.jpg"
  },
  {
    "n": 22,
    "id": "jCRb7WpH6h4",
    "title": "1 Crore, 2 Crore, or 5 Crore? Find YOUR Number Today",
    "guest": "Bhartendra (solo)",
    "cat": "Wealth",
    "views": "786",
    "published": "9 months ago",
    "thumb": "https://i.ytimg.com/vi/jCRb7WpH6h4/hqdefault.jpg"
  },
  {
    "n": 21,
    "id": "o1_3k5EkzZg",
    "title": "The Rupee Keeps Falling… Should You Invest Abroad Too?",
    "guest": "Bhartendra (solo)",
    "cat": "Global",
    "views": "973",
    "published": "10 months ago",
    "thumb": "https://i.ytimg.com/vi/o1_3k5EkzZg/hqdefault.jpg"
  },
  {
    "n": 20,
    "id": "baM9f9oeNEc",
    "title": "Why Smart Investors Don’t Bet Only on India | Devina Mehra on Global Investing",
    "guest": "Devina Mehra",
    "cat": "Global",
    "views": "6.4K",
    "published": "10 months ago",
    "thumb": "https://i.ytimg.com/vi/baM9f9oeNEc/hqdefault.jpg"
  },
  {
    "n": 19,
    "id": "HX4Ln_yjQBc",
    "title": "Step-Up SIP to ₹10 Crore – Pooja Bhinde on Money Psychology",
    "guest": "Pooja Bhinde",
    "cat": "Investing",
    "views": "7.3K",
    "published": "10 months ago",
    "thumb": "https://i.ytimg.com/vi/HX4Ln_yjQBc/hqdefault.jpg"
  },
  {
    "n": 18,
    "id": "ukI6xDsrjyI",
    "title": "Ajit Menon Investment Strategy: 7 Ways to Build Wealth & Financial Freedom",
    "guest": "Ajit Menon",
    "cat": "Wealth",
    "views": "21K",
    "published": "10 months ago",
    "thumb": "https://i.ytimg.com/vi/ukI6xDsrjyI/hqdefault.jpg"
  },
  {
    "n": 17,
    "id": "ch96iqz4wj8",
    "title": "How He Built ₹10 Crore with Just Mutual Funds SIP",
    "guest": "Bhartendra (solo)",
    "cat": "Investing",
    "views": "42K",
    "published": "10 months ago",
    "thumb": "https://i.ytimg.com/vi/ch96iqz4wj8/hqdefault.jpg"
  },
  {
    "n": 16,
    "id": "Fy5Wzb40QhQ",
    "title": "How to Become Rich in India Using Mutual Funds I Dhirendra Kumar I CEO,Value Research",
    "guest": "Dhirendra Kumar",
    "cat": "Investing",
    "views": "187K",
    "published": "10 months ago",
    "thumb": "https://i.ytimg.com/vi/Fy5Wzb40QhQ/hqdefault.jpg"
  },
  {
    "n": 15,
    "id": "oJ0kHSqJaqc",
    "title": "How to Build a Wealth-Ready Portfolio | Vijai Mantri Part 2 |EP 15",
    "guest": "Vijai Mantri",
    "cat": "Wealth",
    "views": "29K",
    "published": "11 months ago",
    "thumb": "https://i.ytimg.com/vi/oJ0kHSqJaqc/hqdefault.jpg"
  },
  {
    "n": 14,
    "id": "Q7UlCPypYlo",
    "title": "Why Investors Earn Just 7% from Funds That Deliver 19% |Vijai Mantri",
    "guest": "Vijai Mantri",
    "cat": "Investing",
    "views": "123K",
    "published": "11 months ago",
    "thumb": "https://i.ytimg.com/vi/Q7UlCPypYlo/hqdefault.jpg"
  },
  {
    "n": 13,
    "id": "OlrHz1Og_kY",
    "title": "Ways to Win In Investing – Behavioral Edge Explained by a CIO",
    "guest": "Bhartendra (solo)",
    "cat": "Behaviour",
    "views": "3.2K",
    "published": "11 months ago",
    "thumb": "https://i.ytimg.com/vi/OlrHz1Og_kY/hqdefault.jpg"
  },
  {
    "n": 12,
    "id": "_pO65w9FnTo",
    "title": "The Truth About Making Money With Mutual Funds | Mutual Fund Nivesh से पैसे बनाने का सही तरीका|Ep12",
    "guest": "Bhartendra (solo)",
    "cat": "Investing",
    "views": "10K",
    "published": "1 year ago",
    "thumb": "https://i.ytimg.com/vi/_pO65w9FnTo/hqdefault.jpg"
  },
  {
    "n": 11,
    "id": "3KvDSkQu-IY",
    "title": "Everything You Need to Know About Mutual Fund Investing – With Niranjan Avasthi |जानिए कैसे और क्यों",
    "guest": "Niranjan Avasthi",
    "cat": "Investing",
    "views": "1K",
    "published": "1 year ago",
    "thumb": "https://i.ytimg.com/vi/3KvDSkQu-IY/hqdefault.jpg"
  },
  {
    "n": 10,
    "id": "07c7HDPBUBE",
    "title": "Retirement Planning in India: What You Need to Know Today | Sneha Jain, CEO WealthTrust",
    "guest": "Sneha Jain",
    "cat": "Retirement",
    "views": "17K",
    "published": "1 year ago",
    "thumb": "https://i.ytimg.com/vi/07c7HDPBUBE/hqdefault.jpg"
  },
  {
    "n": 9,
    "id": "jg9yRvRDqW0",
    "title": "Women, Money & Mindset: Lisa Pallavi Barbora on Taking Charge of Your Finances | EP 09",
    "guest": "Lisa Pallavi Barbora",
    "cat": "Behaviour",
    "views": "556",
    "published": "1 year ago",
    "thumb": "https://i.ytimg.com/vi/jg9yRvRDqW0/hqdefault.jpg"
  },
  {
    "n": 8,
    "id": "LJBgwAlx_MM",
    "title": "Don’t Buy Health Insurance Before Watching ThisI Mahavir Chopra",
    "guest": "Mahavir Chopra",
    "cat": "Retirement",
    "views": "1.8K",
    "published": "1 year ago",
    "thumb": "https://i.ytimg.com/vi/LJBgwAlx_MM/hqdefault.jpg"
  },
  {
    "n": 7,
    "id": "WhrfDxA1d7A",
    "title": "How to Choose The Right Insurance ? |Mahavir Chopra",
    "guest": "Mahavir Chopra",
    "cat": "Retirement",
    "views": "1K",
    "published": "1 year ago",
    "thumb": "https://i.ytimg.com/vi/WhrfDxA1d7A/hqdefault.jpg"
  },
  {
    "n": 6,
    "id": "y467zmb9coo",
    "title": "Wealth & Freedom : You can Have Both I Kirtan Shah",
    "guest": "Kirtan Shah",
    "cat": "Wealth",
    "views": "23K",
    "published": "1 year ago",
    "thumb": "https://i.ytimg.com/vi/y467zmb9coo/hqdefault.jpg"
  },
  {
    "n": 5,
    "id": "qCMA_zCb-38",
    "title": "Many Paths to Financial Heaven I Aashish Sommaiya",
    "guest": "Aashish Sommaiya",
    "cat": "Markets",
    "views": "4.5K",
    "published": "1 year ago",
    "thumb": "https://i.ytimg.com/vi/qCMA_zCb-38/hqdefault.jpg"
  },
  {
    "n": 4,
    "id": "Ms_2WqYOIsY",
    "title": "Should You Buy House? I घर की बात, दिल से",
    "guest": "Abhinav Angirish",
    "cat": "Real Estate",
    "views": "2.9K",
    "published": "1 year ago",
    "thumb": "https://i.ytimg.com/vi/Ms_2WqYOIsY/hqdefault.jpg"
  },
  {
    "n": 3,
    "id": "U9ZrWEL-Jqo",
    "title": "Master Your Emotions & Build Wealth: Expert Wisdom to Smart Investing - Shaymali Basu",
    "guest": "Shaymali Basu",
    "cat": "Wealth",
    "views": "1K",
    "published": "1 year ago",
    "thumb": "https://i.ytimg.com/vi/U9ZrWEL-Jqo/hqdefault.jpg"
  },
  {
    "n": 2,
    "id": "2IFKptd2Qyw",
    "title": "Mutual Fund Investing Insights I Raghav Iyengar",
    "guest": "Raghav Iyengar",
    "cat": "Investing",
    "views": "1.1K",
    "published": "1 year ago",
    "thumb": "https://i.ytimg.com/vi/2IFKptd2Qyw/hqdefault.jpg"
  },
  {
    "n": 1,
    "id": "YH2ZegF1ewk",
    "title": "Essentials of Financial Planning with Mrin Agarwal",
    "guest": "Mrin Agarwal",
    "cat": "Investing",
    "views": "2.2K",
    "published": "1 year ago",
    "thumb": "https://i.ytimg.com/vi/YH2ZegF1ewk/hqdefault.jpg"
  }
];

window.GUESTS = [
  {
    "name": "Vijai Mantri",
    "role": "Founder, VMFS",
    "initials": "VM",
    "eps": 3,
    "ep_ids": [
      28,
      15,
      14
    ],
    "bg": "bg-navy text-mustard"
  },
  {
    "name": "Kirtan Shah",
    "role": "Founder, Credence Wealth",
    "initials": "KS",
    "eps": 2,
    "ep_ids": [
      47,
      6
    ],
    "bg": "bg-mustard text-navy-ink"
  },
  {
    "name": "Neil Borate",
    "role": "Deputy Editor, Mint",
    "initials": "NB",
    "eps": 2,
    "ep_ids": [
      46,
      29
    ],
    "bg": "bg-alert text-cream"
  },
  {
    "name": "Sneha Jain",
    "role": "Fund Manager",
    "initials": "SJ",
    "eps": 2,
    "ep_ids": [
      26,
      10
    ],
    "bg": "bg-navy-ink text-mustard"
  },
  {
    "name": "Mahavir Chopra",
    "role": "Founder, Beshak.org",
    "initials": "MC",
    "eps": 2,
    "ep_ids": [
      8,
      7
    ],
    "bg": "bg-navy text-mustard"
  },
  {
    "name": "Bhalchandra Joshi",
    "role": "Mutual Fund Veteran",
    "initials": "BJ",
    "eps": 1,
    "ep_ids": [
      57
    ],
    "bg": "bg-mustard text-navy-ink"
  },
  {
    "name": "Anupam Tiwari",
    "role": "Head of Equities, Groww Mutual Fund",
    "initials": "AT",
    "eps": 1,
    "ep_ids": [
      55
    ],
    "bg": "bg-alert text-cream"
  },
  {
    "name": "Debashish Bose",
    "role": "Founder, Infinite Circle",
    "initials": "DB",
    "eps": 1,
    "ep_ids": [
      53
    ],
    "bg": "bg-navy-ink text-mustard"
  },
  {
    "name": "Kalpen Parekh",
    "role": "CEO, DSP Mutual Fund",
    "initials": "KP",
    "eps": 1,
    "ep_ids": [
      49
    ],
    "bg": "bg-navy text-mustard"
  },
  {
    "name": "Thomas Priju",
    "role": "Fund Manager",
    "initials": "TP",
    "eps": 1,
    "ep_ids": [
      36
    ],
    "bg": "bg-mustard text-navy-ink"
  },
  {
    "name": "Mohit Bhatia",
    "role": "CEO, Bank of India MF",
    "initials": "MB",
    "eps": 1,
    "ep_ids": [
      35
    ],
    "bg": "bg-alert text-cream"
  },
  {
    "name": "Vinayak Sapre",
    "role": "Financial Coach",
    "initials": "VS",
    "eps": 1,
    "ep_ids": [
      33
    ],
    "bg": "bg-navy-ink text-mustard"
  },
  {
    "name": "CA Anuj Jain",
    "role": "Chartered Accountant",
    "initials": "AJ",
    "eps": 1,
    "ep_ids": [
      30
    ],
    "bg": "bg-navy text-mustard"
  },
  {
    "name": "Devina Mehra",
    "role": "Founder, First Global",
    "initials": "DM",
    "eps": 1,
    "ep_ids": [
      20
    ],
    "bg": "bg-mustard text-navy-ink"
  },
  {
    "name": "Pooja Bhinde",
    "role": "Financial Planner",
    "initials": "PB",
    "eps": 1,
    "ep_ids": [
      19
    ],
    "bg": "bg-alert text-cream"
  },
  {
    "name": "Ajit Menon",
    "role": "Investment Strategist",
    "initials": "AM",
    "eps": 1,
    "ep_ids": [
      18
    ],
    "bg": "bg-navy-ink text-mustard"
  },
  {
    "name": "Dhirendra Kumar",
    "role": "CEO, Value Research",
    "initials": "DK",
    "eps": 1,
    "ep_ids": [
      16
    ],
    "bg": "bg-navy text-mustard"
  },
  {
    "name": "Niranjan Avasthi",
    "role": "Head of Product, Edelweiss MF",
    "initials": "NA",
    "eps": 1,
    "ep_ids": [
      11
    ],
    "bg": "bg-mustard text-navy-ink"
  },
  {
    "name": "Lisa Pallavi Barbora",
    "role": "Financial Journalist",
    "initials": "LB",
    "eps": 1,
    "ep_ids": [
      9
    ],
    "bg": "bg-alert text-cream"
  },
  {
    "name": "Aashish Sommaiya",
    "role": "CEO, WhiteOak Capital",
    "initials": "AS",
    "eps": 1,
    "ep_ids": [
      5
    ],
    "bg": "bg-navy-ink text-mustard"
  },
  {
    "name": "Abhinav Angirish",
    "role": "Founder, Investonline.in",
    "initials": "AA",
    "eps": 1,
    "ep_ids": [
      4
    ],
    "bg": "bg-navy text-mustard"
  },
  {
    "name": "Shaymali Basu",
    "role": "Financial Planner",
    "initials": "SB",
    "eps": 1,
    "ep_ids": [
      3
    ],
    "bg": "bg-mustard text-navy-ink"
  },
  {
    "name": "Raghav Iyengar",
    "role": "CEO, Axis Mutual Fund",
    "initials": "RI",
    "eps": 1,
    "ep_ids": [
      2
    ],
    "bg": "bg-alert text-cream"
  },
  {
    "name": "Mrin Agarwal",
    "role": "Founder, Finsafe",
    "initials": "MA",
    "eps": 1,
    "ep_ids": [
      1
    ],
    "bg": "bg-navy-ink text-mustard"
  }
];
